---
name: 'Update plugins to force cache invalidation'
on: # yamllint disable-line
  schedule:
    - cron: '0 5 * * 4'
  workflow_dispatch:

jobs:
  update_plugins:
    name: Update date on plugins.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create a new branch
        run: git checkout -b "update_plugins"
      - name: update plugins
        run: |
          chmod +x ./ci_scripts/update_plugins.sh
          ./ci_scripts/update_plugins.sh
      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: 'plugins.txt'
          message: 'updated plugins.txt'
          push: origin update_plugins
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: master
          branch: update_plugins
          title: update plugins
          delete-branch: true
          reviewers: hs-llu
          
