on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@v0.18.0
        with:
          bump_version_scheme: minor
      - name: Checkout
        uses: actions/checkout@v2
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: false
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"

