on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@v0.18.0
        with:
          bump_version_scheme: minor
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          # You can change the name of the tag with this input.
          # Default: 'latest'
          tag-name: custom

    # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
    # Optional
    description: Description for the tag
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name.split(',') }}"
          echo "Got release version ${{ steps.release.outputs.version }}"

