---
name: 'Update plugins to force cache invalidation'
on: # yamllint disable-line
  schedule:
    - cron: '0 5 * * 4'
  workflow_dispatch:

jobs:
  update_plugins:
    name: Update date on plugins.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create a new branch
        run: git branch update_plugins && git push origin
      - name: append text to the end of file
        run: echo '# remove' >> new_file.txt
      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: 'new_file.txt'
          message: 'updated plugins.txt'
          branch: update_plugins
#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v3
#         with:
#           base: main
#           branch: update_plugins
