---
name: 'Terraform PR steps'

on:
  - pull_request
env:
  CODE_DIR: code
  TFENV_DIR: tfenv

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          
      - name: debug
        run: ls -a
        
      - name: fetch master
        run: git fetch origin master:master
        
      - name: Get diff size
        run: echo "SIZE=$(git diff --shortstat master . ':(exclude)*.md' | cut -d' ' -f5)" >> $GITHUB_ENV
          
