---
name: 'Terraform PR steps'

on:
  - pull_request
env:
  CODE_DIR: code
  TFENV_DIR: tfenv

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: debug
        run: ls -a
      
      - name: Get diff size
        run: echo "SIZE=$(git diff --shortstat master . ':(exclude)*.md' | cut -d' ' -f5)" >> $GITHUB_ENV
          
